"""add user ownership to expenses

Revision ID: 08bbb52ddef4
Revises: 67c352b5f7ae
Create Date: 2026-09-25 18:28:20.297473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bbb52ddef4'
down_revision = '67c352b5f7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_expenses_user_id_users", 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint("fk_expenses_user_id_users", type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
